[package]
name = "Shimmy"
version = "0.1.0"
lang = "C++20"
pch = "pch.h"

warn-level = "high"
iso-compliant = true

[profile.debug]
# sanitize.address = true
defines = [ "SHMY_DEBUG" ]

[profile.release]
# defines = [ "SHMY_DEBUG" ]

[dependencies]
engine  = { path="../engine" }
audio   = { path="../audio" }
SFUtil  = { path="../../SFUtil" }
NavMesh = { path="../../NavMesh" }
SFML    = { path="../../_Libs/SFML-3", features=[ "graphics" ] }
LuaJIT  = { path="../../_Libs/luajit" }
thread_pool = { headers="../libs/thread_pool/include" }
rapidjson   = { headers="../libs/rapidjson/include" }
utfcpp      = { headers="../libs/utfcpp/source" }
libogg    = { path="../../_Libs/libogg" }
libvorbis = { path="../../_Libs/vorbis" }

